---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: avocado-os
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
    optfix:
      - Mullvad VPN
      - vivaldi
    install:
      - mullvad-vpn
      - vivaldi-stable
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - com.spotify.Client
          - com.github.mtkennerly.ludusavi
          - com.github.wwmm.easyeffects
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          - dev.deedles.Trayscale
          - im.nheko.Nheko
          - info.mumble.Mumble
          - io.github.dimtpap.coppwr
          - io.missioncenter.MissionCenter
          - io.ossia.score
          - io.podman_desktop.PodmanDesktop
          - it.fabiodistasio.AntaresSQL
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
          - net.ankiweb.Anki
          - net.retrodeck.retrodeck
          - org.ardour.Ardour
          - org.audacityteam.Audacity
          - org.fedoraproject.MediaWriter
          - org.filezillaproject.Filezilla
          - org.godotengine.Godot
          - org.inkscape.Inkscape
          - org.mixxx.Mixxx
          - org.mozilla.Thunderbird
          - org.mozilla.firefox
          - org.musescore.MuseScore
          - org.onlyoffice.desktopeditors
          - org.raspberrypi.rpi-imager
          - org.rncbc.qpwgraph
          - org.signal.Signal
          - org.telegram.desktop
          - org.zotero.Zotero
          - page.kramo.Cartridges
  - type: justfiles
    validate: true
  - type: script
    snippets:
      - "mkdir /nix"
  - type: systemd
    system:
      disabled:
        - cec-onboot.service
        - cec-onpoweroff.service
        - cec-onsleep.service
      enabled:
        - mullvad-daemon.service
  - type: signing

