---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: avocado-os
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
    optfix:
      - Mullvad VPN
      - vivaldi
    install:
      - mullvad-vpn
      - vivaldi-stable
  - type: justfiles
    validate: true
  - type: script
    snippets:
      - "mkdir /nix"
  - type: systemd
    system:
      disabled:
        - cec-onboot.service
        - cec-onpoweroff.service
        - cec-onsleep.service
      enabled:
        - mullvad-daemon.service
  - type: signing

