---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: avocado-os
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    optfix:
      - Mullvad VPN
    install:
      - mullvad-vpn
  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.spotify.Client
    user: {}
  - type: justfiles
    validate: true
  - type: signing

