---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: avocado-os
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    optfix:
      - Mullvad VPN
    install:
      - mullvad-vpn
    remove:
      - firefox
      - firefox-langpacks
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}
  - type: signing

